name: PyBuilder Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install pylint
        run: pip install pylint

      - name: Run pylint
        run: pylint src/main/python/calculator.py

  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
           
      - name: Install PyBuilder
        run: | 
          python -m pip install --upgrade pip
          pip install pybuilder
          pip install coverage
     
      - name: Run unit tests with coverage
        run: |
          coverage run -m unittest discover -s src/unittest/python/  # Run tests and measure coverage
          coverage report -m --fail-under=70

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/reports

